[server]
host = "0.0.0.0"
port = 8088
# These are the default values

[proxy]
timeout = 5000
disable = false
# Set to true to have requests not proxied out.

[cache]
dataRoot = "data" # Folder to store the cached responses.
disable = false # Disable caching of responses (or reading of existing cache).
touchFiles = false # Will touch or create (empty) the cache files even if disabled

[mappings.contentful] #contentful
host = "https://cdn.contentful.com"
dir = "contentful"
matchHeaders = false
contentType = "application/json"


[mappings.target] #target
host = "https://dev-target.api.loyalty.com"
dir = "target"
matchHeaders = false
contentType = "application/json"


[mappings.gateway] #target
host = "https://dev.api.loyalty.com"
dir = "gateway"
matchHeaders = false
contentType = "application/json"
